### ISSUE TITLE
No default ~/.homebase.yml upon installation?

### ISSUE THREAD

**Issue by carlcorder** [beakerbrowser/homebase#13]
Hello! What a cool project. I learned about Beaker from a [JSConf video](https://www.youtube.com/watch?v=rJ_WvfF3FN8) and wanted to give it a try.

After building Beaker from [source](https://github.com/beakerbrowser/beaker#building-from-source) I installed homebase:

```
carlc@thinkpad ~ $ npm install -g @beaker/homebase
/home/carlc/.nvm/versions/node/v9.4.0/bin/homebase -> /home/carlc/.nvm/versions/node/v9.4.0/lib/node_modules/@beaker/homebase/index.js

> sodium-native@2.1.6 install /home/carlc/.nvm/versions/node/v9.4.0/lib/node_modules/@beaker/homebase/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"


> utp-native@1.7.2 install /home/carlc/.nvm/versions/node/v9.4.0/lib/node_modules/@beaker/homebase/node_modules/utp-native
> node-gyp-build

+ @beaker/homebase@2.0.1
added 425 packages from 252 contributors in 38.141s
```

Everything looks OK. But, when I run the `homebase` command I get:

```
carlc@thinkpad ~ $ homebase

== Homebase 2.0.1 ==

 ▶ Directory:    /home/carlc/.homebase
 ▶ Ports:        80 (HTTP) 443 (HTTPS)
 ▶ HTTP mirror:  ✖ disabled
 ▶ Lets Encrypt: ✖ disabled
 ▶ Dashboard:    ✖ disabled
 ▶ WebAPI:       ✖ disabled 

fs.js:1399
    throw error;
    ^

Error: watch /home/carlc/.homebase.yml ENOENT
    at _errnoException (util.js:1003:13)
    at FSWatcher.start (fs.js:1397:19)
    at Object.fs.watch (fs.js:1423:11)
    at Object.exports.start (/home/carlc/.nvm/versions/node/v9.4.0/lib/node_modules/@beaker/homebase/lib/server.js:104:18)
    at Object.<anonymous> (/home/carlc/.nvm/versions/node/v9.4.0/lib/node_modules/@beaker/homebase/index.js:19:8)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
```

I checked my `~/.homebase` directory and sure enough `.homebase.yml` isn't there. Should there be a default yml file here or should I just create my own?

Thanks!

**Comment by pfrazee** [comment]
You should create your own, but Homebase could give a better error message. We'll add that to the todos.
