### ISSUE TITLE
Has it installed?

### ISSUE THREAD

**Issue by glowkeeper** [beakerbrowser/homebase#43]
I may or may not have a working installation. I'm running this on Ubuntu 16.04.6:

 `npm install --g @beaker/homebase`

Which runs happily for a few minutes, but then begins to complain. The install ends this way:

````
make: Leaving directory '/home/admin/.nvm/versions/node/v12.6.0/lib/node_modules/@beaker/homebase/node_modules/utp-native/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/admin/.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 3.13.0-44-generic
gyp ERR! command "/home/admin/.nvm/versions/node/v12.6.0/bin/node" "/home/admin/.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/admin/.nvm/versions/node/v12.6.0/lib/node_modules/@beaker/homebase/node_modules/utp-native
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sodium-native@2.4.2 (node_modules/@beaker/homebase/node_modules/sodium-native):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sodium-native@2.4.2 install: `node-gyp-build "node preinstall.js" "node postinstall.js"`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utp-native@1.7.3 (node_modules/@beaker/homebase/node_modules/utp-native):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utp-native@1.7.3 install: `node-gyp-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ @beaker/homebase@2.0.8
added 454 packages from 251 contributors in 138.277s
````
Er, did it install, or not?

**Comment by pfrazee** [comment]
Hmm! That's odd. Basically it failed to build the native crypto code (fallback to slower JS) and failed to install the utp networking code (fallback to TCP). It's not a blocker but it's not ideal. Since it's a homebase instance, usually TCP will be enough, and the JS crypto can work.

I'm unsure why the build would have failed. Maybe missing compilation tools? There's not a lot of info in that log.

**Comment by glowkeeper** [comment]
@pfrazee - I installed all the dependencies listed, namely:

`apt-get install libtool m4 automake libcap2-bin build-essential`

I can supply the whole log, if you wish?

**Comment by pfrazee** [comment]
@glowkeeper hmm only if you think it has more info.

**Comment by glowkeeper** [comment]
Not sure I'm the best person to judge! Attached:

[log.txt](https://github.com/beakerbrowser/homebase/files/3418576/log.txt)

**Comment by pfrazee** [comment]
Oh okay, I know the problem. We havent updated those deps for node 12 yet. Can you downgrade to 11?

**Comment by glowkeeper** [comment]
@pfrazee - aha! Probably! Thanks...I'll let you know how I get on.

ps. when will node 12 be supported?

**Comment by pfrazee** [comment]
Very soon. Just a lot of API changes for native modules in 12

**Comment by glowkeeper** [comment]
Cool - downgraded to node 11.15.0 (nvm makes managing multiple versions of node a breeze ;) ), and I think I'm good now....

**Comment by pfrazee** [comment]
Good deal. Sorry for the trouble!

**Comment by glowkeeper** [comment]
@pfrazee - no problem - thanks for getting back to me so quickly!

ps. I've got homebase happily serving http://4b1bdf7b0f6beeadab5dadaf019cddbc94f618792ea30b8a2f5d957267d5bd92/

...which I've loaded into Firefox via the DAT P2P Protocol extension - it's a blockchain app', so that allows me to use MetaMask...

Thanks!

**Comment by pfrazee** [comment]
Sweet!
